spring:
  datasource:
    url: jdbc:mysql:///size_design?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    password: qing1016..
    password: Root123!!
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  security:
      basic:
        enabled: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
    timeout: 1000ms

server:
  port: 8068